### ISSUE TITLE
Cannot use the tenor API option

### ISSUE THREAD

**Issue by ngophuong** [TomCasavant/GiphyMaubot#12]
Hi there,
First of all, Thank you for your work 👍 
Just want to report issues with my setup have issues with connection to host g.tenor.com:443 

The option with giphy API work fine.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 970, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/client/syncer.py", line 236, in _catch_errors
    await handler(data)
  File "/opt/maubot/maubot/handlers/command.py", line 154, in __call__
    return await self.__mb_func__(self.__bound_instance__, evt, **call_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/casavant.tom.giphy-v3.3.0.mbp/giphy.py", line 97, in handler
    async with self.http.get(
  File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: **Cannot connect to host g.tenor.com:443** ssl:default [Connection reset by peer]

```

**Comment by TomCasavant** [comment]
I'll take a look at this when I get a chance, but are you using a v1 or v2 version of the tenor API key?

**Comment by ngophuong** [comment]
Hi there,
I got my API tenor from latest instruction via https://developers.google.com/tenor/guides/quickstart - 
It's not mention V2 but only mention API V1 is no longer support

**Comment by TomCasavant** [comment]
Okay, I tried it with a v2 API key and I can't seem to recreate your issue.

Can you confirm that your tenor_api_key is correct and that your tenor api version is set to v2 in the config file?

**Comment by ngophuong** [comment]
Thank you for your quick update Tom . It's seem that is my internet provider / setup have some issues with secure connection.
![image](https://github.com/TomCasavant/GiphyMaubot/assets/47920592/e5cc24ed-3f33-48b9-b163-6c7b3c6b8aa8)
